name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: liatrio-exercise-spring2023

jobs:

  build-test-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t cfculler/liatrio:latest .
      
    - name: Start Server
      run: docker run -d -p 80:80 cfculler/liatrio:latest && sleep 3
      
    - name: Run Tests
      uses: liatrio/github-actions/apprentice-action@master
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    
    - name: Push the image to Docker Hub
      run: docker push cfculler/liatrio:latest

    # Extra Credit Portion Below

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.2
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker Client
      run: gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry
      run: |-
        docker tag cfculler/liatrio:latest gcr.io/liatrio-exercise-spring2023/liatrio-ci:latest
        docker push gcr.io/liatrio-exercise-spring2023/liatrio-ci:latest

    - name: Deploy new image
      run: gcloud run deploy liatrio-ci --image gcr.io/liatrio-exercise-spring2023/liatrio-ci:latest --region us-central1 --platform managed
      #id: deploy
      #uses: google-github-actions/deploy-cloudrun@v0
      #with:
        #service: liatrio-ci
        #region: us-central1
        #source: gcr.io/liatrio-exercise-spring2023/liatrio-ci:latest
      
      
      
